name: CI Workflow MLflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas numpy

      - name: Reset MLflow Database / Artifacts
        run: |
          # Menghapus direktori mlruns lama jika ada agar tidak konflik versi migrasi alembic
          rm -rf mlruns

      - name: Run MLflow Project
        shell: bash -el {0}
        run: |
          eval "$(conda shell.bash hook)"
          mlflow run MLProject --backend local --env-manager=conda
